name: Kargotakip CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKG_VERSION: ${{ github.sha }}
      PROJECT_PATH: /usr/local/kargo-takip-backend
      SERVICE_PATH: /lib/systemd/system
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: echo $PKG_VERSION
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: PKG_VERSION, PROJECT_PATH, SERVICE_PATH
          script: |
            cmp --silent $GITHUB_WORKSPACE/kargotakip.service $SERVICE_PATH/kargotakip.service || sudo cp -rf $GITHUB_WORKSPACE/kargotakip.service $SERVICE_PATH;sudo systemctl daemon-reload
            sudo cp -rf $GITHUB_WORKSPACE/. $PROJECT_PATH
            sudo rm -rf $PROJECT_PATH/.git;sudo rm -rf $PROJECT_PATH/kargotakip.service;
            cd $PROJECT_PATH;sudo npm install
            sudo chown -R support:support $PROJECT_PATH
            sudo systemctl restart kargotakip.service
